spring:
  datasource:
    host: localhost
    port: 5432
    db: postgres
    username: postgres
    password: example

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
