spring:
  datasource:
    host: localhost
    port: 5432
    db: postgres
    username: postgres
    password: example

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      data-locations:
        - classpath:initDBData.sql
